### ISSUE TITLE
Sitemap.xml returning 404 on production machine

### ISSUE THREAD

**Issue by scottschluer** [maartenba/MvcSiteMapProvider#124]
MvcSiteMapProvider generates a sitemap.xml file when I request it at http://localhost/sitemap.xml, but upon pushing the project to production, http://www.website.com/sitemap.xml throws a 404. Any ideas why? This is an ASP.NET MVC 4 project.

**Comment by tomaskikutis** [comment]
I was also having a similar problem. Sitemap would become inaccessible after registering a route with root dynamic segment like this:

```
routes.MapRoute(
    name: "FirstLevelCategory",
    url: "{urlString}",
    defaults: new { controller = "Category", action = "Index" }
);
```

The solution which worked for me was registering sitemap routes **before** application routes

```
protected void Application_Start()
{
	...
	XmlSiteMapController.RegisterRoutes(RouteTable.Routes);
	RouteConfig.RegisterRoutes(RouteTable.Routes);
	...
}
```
