### ISSUE TITLE
SiteMaps.Current.RootNode returns null

### ISSUE THREAD

**Issue by ravipunjwani** [maartenba/MvcSiteMapProvider#225]
Hi,

I have an issue in accessing the sitemap in the code.

I have a [childaction] method which is configured with [outputcache].

Everything works well until there is no [outputcache]. But with [outputcache] attribute, I get null values in "SiteMaps.Current.RootNode" and "SiteMaps.Current.CurrentNode".

Can you suggest me what is the problem.

Thanks in advance,
- Ravi

**Comment by metzing** [comment]
Hi there NightOwl

I'm also trying to cache a generated navbar using `[OutputCache]`. When I remove the attribute everything works as expected.

Here is the Controller and Action I'm (planning on) using to render the component.
```
public class ComponentsController : Controller
{
    [OutputCache(Duration = 3600)]
    public ActionResult SiteMapNavbarItems()
    {
        return PartialView();
    }
}
```
In the SiteMapNavbarItems veiw I render the SiteMap using the following line of code:
```
@Html.MvcSiteMap().Menu("XNavMenu")
```
When I remove the `[OutputCache]` attribute the `CurrentNode` and `RootNode` properties of `SiteMaps.Current` are set as expected, but when running with the attrubute "on", they are both `null`.


Another odd behaviour is the fact that when calling the above action directly from a browser I get the expected output. At this state `CurrentNode` is `null` and `RootNode` is the expected root node. If I call the action I actually want afterwards, it renders again (for some reason doesn't use the version that could have been cached).

Really looking forward for your ideas,
MM
