### ISSUE TITLE
<Iframe> in razor view stops dropdown menu working

### ISSUE THREAD

**Issue by keithd99** [maartenba/MvcSiteMapProvider#311]
When I drop an iFrame tag into my razor view, dropdown menu stops working (IE and Chrome)

Nothing happens - just a hash tag is appended to url in browser window:
http://localhost/Project/View#

**Comment by NightOwl888** [comment]
I am closing this as it is really not a question about MvcSiteMapProvider, but it sounds more like an issue with HTML/CSS/JavaScript.
