### ISSUE TITLE
What is the preservedRouteParameters attribute syntax for multiple route values?

### ISSUE THREAD

**Issue by KirkGamesLLC** [maartenba/MvcSiteMapProvider#315]
What is the syntax for preserving multiple route parameters?

I have tried
preservedRouteParameters = "dr, topnav" failed
preservedRouteParameters = "dr topnav" failed
preservedRouteParameters = "dr,topnav" failed

**Comment by ik-j** [comment]
I have a site abc.com for almost 200,000 PARTS which are in DB. I have custom links i.e. abc.com/part-number. Part-number can be any string like "123", "87686-ABC" etc. I actually have a page requestQuote.cshtml where the info for the specific part in the link is shown. So i hv virtually over 200,000 links. Now I am trying to use <mvcSiteMapNode title="Parts" controller="Home" action="RequestQuote" preservedRouteParameters="id" />
