### ISSUE TITLE
Cache may crash if a dependency change before the lazylock object is filled

### ISSUE THREAD

**Issue by mnivet** [maartenba/MvcSiteMapProvider#352]
In AspNetCacheProvider<T> and RuntimeCacheProvider<T> when an item is removed the method Get of the LazyLock class is called with a null parameter.

This could crash is the Get method has never been called before on that LazyLock instance.

While it could be reasonable to think that the instance has been read at least once before it is deleted, in fact it's not always true.

In particular if one of the dependency change before the first call to that Get method. This first call seems to be performed by the MicroCache class. But nothing guaranty that there is no dependency change between the add to the cache and the first call (In our system with complex cache dependencies, I've experience the problem multiple times...)

One solution that I try and that works is to call lazy.Get(loadFunction); in MicroCache class before adding the lazylock instance to the cache provider.
Once you do that, using a LazyLock wrapper around the stored object seems useless... However it's also difficult to completely remove this object from the MvcSiteMap code without performing a breaking change on the API as it is exposed by the ICacheProvider interface.

Another solution could be to modify the LazyLock implementation to not crash when the activator parameter is null (by setting the value to default(TValue) ?), but this seems not totally working as I end up with a null when calling SiteMaps.Current later in my application...

Or once again choose a solution that will break your public API and abandon your LazyLock class and replace it by System.Lazy<T> which support thread safe lock and take the activator method in the constructor, which avoid to be unable to know how to retrieve the value as its occurs during the removed from cache events... But I'm not sure that calling the loadfuntion provide to the MicroCache class during the item removed event of cache provider has a real utility. In fact as I was saying for the first solution, I'm not sure that using a lazy wrapper has a real utility...

Whatever solution you choose I'm pretty interested in order to remove our dirty workaround code...

**Comment by rlerch** [comment]
Was this error fixed in any version of this library?

**Comment by justinelhiggins** [comment]
This still seems to occur for dynamic pages in 4.6.26.

Is there a way to just disable the cache?
