### ISSUE TITLE
Localization without .resx files

### ISSUE THREAD

**Issue by vvk1267** [maartenba/MvcSiteMapProvider#364]
Hi,

I am using mvcSiteMapProvider for breadcrumbs in my project. For localization, I am fetching the resources from the database on start of the application and then filling up the cache (`System.Web.HttpContext.Current.Cache["languageList"]`) containing the resources' key-value pair. 

```
public DisplayResource(string value)
        : base(GetResourceValue(value))
    {

    }
```

As I am using this approach to localize the website, I do not want to create resource files just for mvcSiteMapProvider. So, how can I localize the breadcrumbs without using the Global Resource files?

**Comment by mirac61** [comment]
Hello, I have same problem. I using Autofac for dependency container. And I want use my own string localization on sitemap titles(not resource file). Anyone succed it?
