### ISSUE TITLE
Multiple nodes to point to the same action but with diferents url parameters

### ISSUE THREAD

**Issue by gregorypilar** [maartenba/MvcSiteMapProvider#372]
HI,

I have a four dynamic nodes  that point to the same controller and action , I generated the nodes lik this : 
```code
  foreach (var canal in canales)
            {
                var myNode = new DynamicNode
                {
                    Title = canal.Nombre,
                    Description = canal.Nombre,
                    Controller = "PeriodoCorte",
                    Action = "CortesPorCanal",
                    ParentKey ="a939d77a-bfea-49a5-898a-2aa50f9b7f99",
                    Key = Guid.NewGuid().ToString(),
                    CanonicalKey = "a939d77a-bfea-49a5-898a-2aa50f9b7f99",
                    Roles = new List<string>()
                };
                myNode.Roles.Add(canal.CodigoCanal);
                
                //
                myNode.RouteValues.Add("canalId", canal.Id);
                myNode.RouteValues.Add("corteId", canal.CorteActual.Id);
                //
                returnValue.Add(myNode);
            }
````

The only difference on the nodes are the routevalues , and the problem that Im facing is , when I click  a node always the value the current node is equal to the first node that is generated , no the node that I clicked 

there is a way using SiteMaps.Current o something that I can get the right node

**Comment by NightOwl888** [comment]
Since you haven't provided a way to duplicate this issue, I am closing it for now. Feel free to reopen it if you are still seeing this behavior and can provide more info.
