### ISSUE TITLE
MVC Hang / Thread issue

### ISSUE THREAD

**Issue by AndiRudi** [maartenba/MvcSiteMapProvider#379]
Hi,

over the last weeks I had the problem that IISExpress hangs from time to time. Sometimes every second run of the mvc app ended with a browser not finishing the response. I may have identified an issue with the sitemap provider here. I've used the poor mans DI and when I break VS then I can see on a Thread that there is the sitemap provider involved. 

I then deinstalled the MVC5 packaged and add the method  MvcSiteMapProvider.DI.Composer.Compose(); manually to my application_start and I get the exact same thing here. Please hava a lock at the stack trace. The iisexpress/vs hangs forever at this stage. Seems to be kind of a lock / thread wait?

Thanks
Andi
![hang](https://cloud.githubusercontent.com/assets/6254862/5788899/beb16e7c-9e52-11e4-80d6-4ad558f1543b.PNG)

**Comment by NightOwl888** [comment]
Based on the stack trace, this appears to be a problem related to the System.Runtime.Caching.MemoryCache.Default instance. I have always treated it as sort of a black box process, sort of like System.Web.Caching, but apparently it has other dependencies I was previously unaware of.

First of all, the poor man's DI container uses the default cache instance. There are [configuration file settings](http://msdn.microsoft.com/en-us/library/dd941872(v=vs.110).aspx) that can be used to put a cap on the amount of memory that is allowed to be used for a cache. These settings could be in your web.config, the machine web.config, or the machine.config file for your .NET framework version and bitness, so there quite a few places where these settings could be lurking:

```xml
<configuration>
  <system.runtime.caching>
    <memoryCache>
      <namedCaches>
          <add name="default" 
               cacheMemoryLimitMegabytes="0" 
               physicalMemoryPercentage="0"
               pollingInterval="00:02:00" />
      </namedCaches>
    </memoryCache>
  </system.runtime.caching>
</configuration>
```
According to the documentation, however, it should just remove cache entries (not hang) if it is set too low. But it might be worth a try to experiment with removing these settings if they exist on your server.

Following your stack trace further, it seems to be hanging when creating the [performance counters](http://msdn.microsoft.com/en-us/library/system.diagnostics.performancecounter%28v=vs.110%29.aspx) within the default MemoryCache instance, specifically when opening the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\.NET Memory Cache 4.0\Performance`. There are 7 performance counters that it is attempting to create within this key:

```c#
private void InitDisposableMembers(string cacheName)
{
    bool flag = true;
    try
    {
        StringBuilder builder = (s_appId != null) ? new StringBuilder(s_appId + ":" + cacheName) : new StringBuilder(cacheName);
        for (int i = 0; i < builder.Length; i++)
        {
            switch (builder[i])
            {
                case '/':
                case '\\':
                case '#':
                    builder[i] = '_';
                    break;

                case '(':
                    builder[i] = '[';
                    break;

                case ')':
                    builder[i] = ']';
                    break;
            }
        }
        string instanceName = builder.ToString();
        this._counters = new PerformanceCounter[7];
        this._counterValues = new long[7];
        this._counters[0] = new PerformanceCounter(".NET Memory Cache 4.0", "Cache Entries", instanceName, false);
        this._counters[1] = new PerformanceCounter(".NET Memory Cache 4.0", "Cache Hits", instanceName, false);
        this._counters[2] = new PerformanceCounter(".NET Memory Cache 4.0", "Cache Hit Ratio", instanceName, false);
        this._counters[3] = new PerformanceCounter(".NET Memory Cache 4.0", "Cache Hit Ratio Base", instanceName, false);
        this._counters[4] = new PerformanceCounter(".NET Memory Cache 4.0", "Cache Misses", instanceName, false);
        this._counters[5] = new PerformanceCounter(".NET Memory Cache 4.0", "Cache Trims", instanceName, false);
        this._counters[6] = new PerformanceCounter(".NET Memory Cache 4.0", "Cache Turnover Rate", instanceName, false);
        flag = false;
    }
    finally
    {
        if (flag)
        {
            this.Dispose();
        }
    }
}
```

Here are the exported registry keys from my system:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\.NET Memory Cache 4.0]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\.NET Memory Cache 4.0\Linkage]
"Export"=""

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\.NET Memory Cache 4.0\Performance]
"CategoryOptions"=dword:00000003
"Counter Types"=hex:36,00,35,00,35,00,33,00,36,00,00,00,36,00,35,00,35,00,33,\
  00,36,00,00,00,35,00,33,00,37,00,30,00,30,00,33,00,30,00,30,00,38,00,00,00,\
  31,00,30,00,37,00,33,00,39,00,33,00,39,00,34,00,35,00,39,00,00,00,36,00,35,\
  00,35,00,33,00,36,00,00,00,36,00,35,00,35,00,33,00,36,00,00,00,32,00,37,00,\
  32,00,36,00,39,00,36,00,33,00,32,00,30,00,00,00,00,00
"Close"="ClosePerformanceData"
"FileMappingSize"=dword:00020000
"Counter Names"=hex:43,00,61,00,63,00,68,00,65,00,20,00,48,00,69,00,74,00,73,\
  00,00,00,43,00,61,00,63,00,68,00,65,00,20,00,4d,00,69,00,73,00,73,00,65,00,\
  73,00,00,00,43,00,61,00,63,00,68,00,65,00,20,00,48,00,69,00,74,00,20,00,52,\
  00,61,00,74,00,69,00,6f,00,00,00,43,00,61,00,63,00,68,00,65,00,20,00,48,00,\
  69,00,74,00,20,00,52,00,61,00,74,00,69,00,6f,00,20,00,42,00,61,00,73,00,65,\
  00,00,00,43,00,61,00,63,00,68,00,65,00,20,00,54,00,72,00,69,00,6d,00,73,00,\
  00,00,43,00,61,00,63,00,68,00,65,00,20,00,45,00,6e,00,74,00,72,00,69,00,65,\
  00,73,00,00,00,43,00,61,00,63,00,68,00,65,00,20,00,54,00,75,00,72,00,6e,00,\
  6f,00,76,00,65,00,72,00,20,00,52,00,61,00,74,00,65,00,00,00,00,00
"IsMultiInstance"=dword:00000001
"Open"="OpenPerformanceData"
"Collect"="CollectPerformanceData"
"Library"=hex(2):25,00,73,00,79,00,73,00,74,00,65,00,6d,00,72,00,6f,00,6f,00,\
  74,00,25,00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,6e,\
  00,65,00,74,00,66,00,78,00,70,00,65,00,72,00,66,00,2e,00,64,00,6c,00,6c,00,\
  00,00
```

Well, clearly we are now talking about .NET framework code, not MvcSiteMapProvider. There might be something configuration related on your machine that is causing performance counters not to be created, such as a registry permission issue. You could attempt to use the System.Runtime.Caching.MemoryCache.Default instance (or a named instance) or creating performance counters manually to see if you can reproduce the problem and perhaps gain more insight as to why it is hanging.

If you come to a dead end there, you could circumvent this problem entirely by switching to the [AspNetCacheProvider](https://github.com/maartenba/MvcSiteMapProvider/blob/master/src/MvcSiteMapProvider/MvcSiteMapProvider/Caching/AspNetCacheProvider.cs) that is based on System.Web.Caching. You just need to install [MvcSiteMapProvider.MVC5.DI.Unity.Modules](https://www.nuget.org/packages/MvcSiteMapProvider.MVC5.DI.Unity.Modules/) package, follow the [instructions in the ReadMe](https://github.com/maartenba/MvcSiteMapProvider/tree/master/src/MvcSiteMapProvider/CodeAsConfiguration/Unity/DI/Unity) to wire it into your current Unity configuration. Then you can swap out the cache provider code in the MvcSiteMapProviderContainerExtension class. It will look like this by default:

```c#
this.Container.RegisterInstance<System.Runtime.Caching.ObjectCache>(System.Runtime.Caching.MemoryCache.Default);
this.Container.RegisterType(typeof(ICacheProvider<>), typeof(RuntimeCacheProvider<>));
this.Container.RegisterType<ICacheDependency, RuntimeFileCacheDependency>(
	"cacheDependency", new InjectionConstructor(absoluteFileName));
```

You just need to change those lines to:

```c#
this.Container.RegisterType(typeof(ICacheProvider<>), typeof(AspNetCacheProvider<>));
this.Container.RegisterType<ICacheDependency, AspNetFileCacheDependency>(
	"cacheDependency", new InjectionConstructor(absoluteFileName));
```

**Comment by AndiRudi** [comment]
I tried to reproduce the issue with a command line project calling the MemoryCache but there weren't any issues. It might be somewhat complex to find the error. 

I change my code to use the Unity-Integration and the issue changed slightly. The new hold is now on the line where the caching gets registered

    this.Container.RegisterInstance<System.Runtime.Caching.ObjectCache>(System.Runtime.Caching.MemoryCache.Default);

So i switche to the AspNetCacheProvider as u mentioned and for know the issue is gone. I'll try that for a while.

**Comment by NightOwl888** [comment]
Good to hear you got it working.

It occurred to me that although the MSDN docs say that the MemoryCache will remove entries if the cache is full, MvcSiteMapProvider uses 1 entry per SiteMap instance. So, if the SiteMap requires more memory than the threshold that the configuration is set for, it very well could hang because there are no other nodes to remove.

Anyway, there is really no downside to using the AspNetCacheProvider other than the fact it is not as configurable or extensible as the ObjectCache. But since it is the configuration that seems to be your problem, you are better off with it.

**Comment by moejoe** [comment]
Hi, 
we had the same problem for the past weeks, and i found some information that seems to confirm, that the problem is actually in the performance counter library. 
See : http://www.zpqrtbnk.net/posts/appdomains-threads-cultureinfos-and-paracetamol for detailed information, and a fix.
