### ISSUE TITLE
Using MEF based controllers -- Bad Controller Class Names

### ISSUE THREAD

**Issue by nrm101** [maartenba/MvcSiteMapProvider#384]
First out, this isn't a bug per say just will be helpfull for the next guy scratching his head.  I ran into an issue were I had mistakenly created a controller and called it "EmailControler",  Leaving out the extra "L" in controller.  Now you would think all kinds of things wouldn't work with the project, but because I had a baseclass controller that was MEF based, and Exported it was resolving the Controller even thou it wasn't correct from an MVC perspective.  So the issue shows its self with Attributes

in ReflectionSiteMapNodeProviders, line 204; your trying to get the Controller, via substring, and in my Scenario above, it gets a ArgumentOutOfRangeException : {"Length cannot be less than zero.\r\nParameter name: length"}.  

So not sure what the right fix for you would be, other than from an MVC perspective everything works fine on my end because my Export Name was really what was being resolved which was "Email" vs. the traditional Controller name minus the substring "Controller"

Anyway Awesome project keep it up!

**Comment by NightOwl888** [comment]
Thanks for the feedback. However, I am closing this because it technically is not an issue to be worked on, but it will still remain here for informational purposes in case someone runs into the same error message.
