### ISSUE TITLE
Multiple Browser opened at the same time

### ISSUE THREAD

**Issue by journeyfitnesscompany** [maartenba/MvcSiteMapProvider#388]
Hello Guys,

I am experiencing this consistent error where in one of my application is open in chrome and all the menus are showing as it should be. The user in chrome is a front end user of the application. When I open another instance of my application in Safari and logged in as a back end user, then go back to chrome and hit refresh, the menus disappear.

Any Idea what's causing it?

Regards,
Mark

**Comment by NightOwl888** [comment]
Not sure. There were issues like this in v3 because of shared caching between users.

Could you create a demo application with the behavior so I can take a look?

**Comment by NightOwl888** [comment]
Were you able to work out this issue?

**Comment by NightOwl888** [comment]
Closing for lack of response for more than 2 months.
