### ISSUE TITLE
Disable mvcSiteMapProvider

### ISSUE THREAD

**Issue by Alex-Sokolov** [maartenba/MvcSiteMapProvider#390]
Which is best way to completely disable generating nodes? Sometimes in debug it can take time to wait when generate all nodes and switch off will be helpful.

**Comment by NightOwl888** [comment]
This isn't a use case I have considered, but you might be able to work around the issue by using [dynamic node providers](https://github.com/maartenba/MvcSiteMapProvider/wiki/Defining-Sitemap-Nodes-using-IDynamicNodeProvider) with conditional logic that detects when you are in debug mode, and returning no nodes in that case.

```c#
public class MyDynamicNodeProvider
	: DynamicNodeProviderBase
{
	public override IEnumerable<DynamicNode> GetDynamicNodeCollection(ISiteMapNode node)
	{
		if (!HttpContext.Current.IsDebuggingEnabled) 
		{
	
			// Return nodes from your data source
			
		}
		else
		{
			return new List<DynamicNode>();
		}
	}
}
```

If using external DI, you could do this more cleanly by adding a decorator class for `ISiteMapNodeProvider` and wrapping the `CompositeSiteMapNodeProvider` in your DI configuration. Note that you must always have 1 node for the home page, but all other nodes are optional. 

```c#
public class DebuggableSiteMapNodeProviderDecorator 
	: ISiteMapNodeProvider
{
	private readonly ISiteMapNodeProvider innerProvider;
	
	public DebuggableSiteMapNodeProviderDecorator(ISiteMapNodeProvider innerProvider)
	{
		if (innerProvider == null)
			throw new ArgumentNullException("innerProvider");
		this.innerProvider = innerProvider;
	}

	#region ISiteMapNodeProvider Members

	public IEnumerable<ISiteMapNodeToParentRelation> GetSiteMapNodes(ISiteMapNodeHelper helper)
	{
		if (!HttpContext.Current.IsDebuggingEnabled) 
		{
			return this.innerProvider.GetSiteMapNodes(helper);
		}
		else
		{
			// Create node for home page
            var nodeParentMap = helper.CreateNode(key: "Home", parentKey: "", sourceName: this.GetType().Name);
            var node = nodeParentMap.Node;
			
			node.Title = "Home";
			node.Controller = "Home";
			node.Action = "Index";
			
			yield return nodeParentMap;
		}
	}

	#endregion
}
```

And then use the decorator to wrap your existing SiteMapNodeProviders in your DI setup.

```c#
// Register the sitemap node providers
var siteMapNodeProvider = this.For<ISiteMapNodeProvider>().Use<CompositeSiteMapNodeProvider>()
	.EnumerableOf<ISiteMapNodeProvider>().Contains(x =>
	{
		x.Type<XmlSiteMapNodeProvider>()
			.Ctor<bool>("includeRootNode").Is(true)
			.Ctor<bool>("useNestedDynamicNodeRecursion").Is(false)
			.Ctor<IXmlSource>().Is(xmlSource);
		x.Type<ReflectionSiteMapNodeProvider>()
			.Ctor<IEnumerable<string>>("includeAssemblies").Is(includeAssembliesForScan)
			.Ctor<IEnumerable<string>>("excludeAssemblies").Is(new string[0]);
	});

// Register the debugger decorator
var debuggableSiteMapNodeProvider = this.For<ISiteMapNodeProvider().Use<DebuggableSiteMapNodeProviderDecorator>()
	.Ctor<ISiteMapNodeProvider>().Is(siteMapNodeProvider);

// Register the sitemap builders
var builder = this.For<ISiteMapBuilder>().Use<SiteMapBuilder>()
	.Ctor<ISiteMapNodeProvider>().Is(debuggableSiteMapNodeProvider);
```

**Comment by Alex-Sokolov** [comment]
Thanks for answer!
I use same workaround but with conditional compilation symbols:
```c#
public override IEnumerable<DynamicNode> GetDynamicNodeCollection (ISiteMapNode node)
{
	var nodesList = new List<DynamicNode>();

	#if !INCLUDE_NODES
	return nodesList;
	#endif

	...
}
```
But with workaround I need also to set false in web.config
```xml
<add key="MvcSiteMapProvider_ScanAssembliesForSiteMapNodes" value="true" />
```
That needed to hide error about nodes without parents (some static nodes hardcoded to some of created in DynamicNodeProvider)

Therefore I ask, maybe there is best way in one-click-way :D

**Comment by brahbrah89** [comment]
Skip to content
This repository
Search
Pull requests
Issues
Gist
 @brahbrah89
 Watch 69
  Star 439
 Fork 172 maartenba/MvcSiteMapProvider
 Code  Issues 49  Pull requests 2  Wiki  Pulse  Graphs
New issue
Disable mvcSiteMapProvider #390
 Open	Alex-Sokolov opened this issue on Apr 29, 2015 · 2 comments
Labels

is:Feature Request
Milestone

No milestone
Assignees

No one assigned
2 participants

@Alex-Sokolov @NightOwl888
Notifications

  Subscribe
You’re not receiving notifications from this thread.
@Alex-Sokolov
 
Alex-Sokolov commented on Apr 29, 2015
Which is best way to completely disable generating nodes? Sometimes in debug it can take time to wait when generate all nodes and switch off will be helpful.
@NightOwl888
 Collaborator
NightOwl888 commented on Apr 29, 2015
This isn't a use case I have considered, but you might be able to work around the issue by using dynamic node providers with conditional logic that detects when you are in debug mode, and returning no nodes in that case.

public class MyDynamicNodeProvider
    : DynamicNodeProviderBase
{
    public override IEnumerable<DynamicNode> GetDynamicNodeCollection(ISiteMapNode node)
    {
        if (!HttpContext.Current.IsDebuggingEnabled) 
        {

            // Return nodes from your data source

        }
        else
        {
            return new List<DynamicNode>();
        }
    }
}
If using external DI, you could do this more cleanly by adding a decorator class for ISiteMapNodeProvider and wrapping the CompositeSiteMapNodeProvider in your DI configuration. Note that you must always have 1 node for the home page, but all other nodes are optional.

public class DebuggableSiteMapNodeProviderDecorator 
    : ISiteMapNodeProvider
{
    private readonly ISiteMapNodeProvider innerProvider;

    public DebuggableSiteMapNodeProviderDecorator(ISiteMapNodeProvider innerProvider)
    {
        if (innerProvider == null)
            throw new ArgumentNullException("innerProvider");
        this.innerProvider = innerProvider;
    }

    #region ISiteMapNodeProvider Members

    public IEnumerable<ISiteMapNodeToParentRelation> GetSiteMapNodes(ISiteMapNodeHelper helper)
    {
        if (!HttpContext.Current.IsDebuggingEnabled) 
        {
            return this.innerProvider.GetSiteMapNodes(helper);
        }
        else
        {
            // Create node for home page
            var nodeParentMap = helper.CreateNode(key: "Home", parentKey: "", sourceName: this.GetType().Name);
            var node = nodeParentMap.Node;

            node.Title = "Home";
            node.Controller = "Home";
            node.Action = "Index";

            yield return nodeParentMap;
        }
    }

    #endregion
}
And then use the decorator to wrap your existing SiteMapNodeProviders in your DI setup.

// Register the sitemap node providers
var siteMapNodeProvider = this.For<ISiteMapNodeProvider>().Use<CompositeSiteMapNodeProvider>()
    .EnumerableOf<ISiteMapNodeProvider>().Contains(x =>
    {
        x.Type<XmlSiteMapNodeProvider>()
            .Ctor<bool>("includeRootNode").Is(true)
            .Ctor<bool>("useNestedDynamicNodeRecursion").Is(false)
            .Ctor<IXmlSource>().Is(xmlSource);
        x.Type<ReflectionSiteMapNodeProvider>()
            .Ctor<IEnumerable<string>>("includeAssemblies").Is(includeAssembliesForScan)
            .Ctor<IEnumerable<string>>("excludeAssemblies").Is(new string[0]);
    });

// Register the debugger decorator
var debuggableSiteMapNodeProvider = this.For<ISiteMapNodeProvider().Use<DebuggableSiteMapNodeProviderDecorator>()
    .Ctor<ISiteMapNodeProvider>().Is(siteMapNodeProvider);

// Register the sitemap builders
var builder = this.For<ISiteMapBuilder>().Use<SiteMapBuilder>()
    .Ctor<ISiteMapNodeProvider>().Is(debuggableSiteMapNodeProvider);
@Alex-Sokolov
 
Alex-Sokolov commented on Apr 30, 2015
Thanks for answer!
I use same workaround but with conditional compilation symbols:

public override IEnumerable<DynamicNode> GetDynamicNodeCollection (ISiteMapNode node)
{
    var nodesList = new List<DynamicNode>();

    #if !INCLUDE_NODES
    return nodesList;
    #endif

    ...
}
But with workaround I need also to set false in web.config

<add key="MvcSiteMapProvider_ScanAssembliesForSiteMapNodes" value="true" />
That needed to hide error about nodes without parents (some static nodes hardcoded to some of created in DynamicNodeProvider)

Therefore I ask, maybe there is best way in one-click-way to disable all dynamic nodes providers and set off searching MvcSiteMapProvider attributes :D
 @NightOwl888NightOwl888 added the is:Feature Request label on Sep 4, 2015
@brahbrah89
  
            
 
Write  Preview

Leave a comment
Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.
 Styling with Markdown is supported
Comment
Contact GitHub API Training Shop Blog About
© 2016 GitHub, Inc. Terms Privacy Security Status Help
