### ISSUE TITLE
Why MvcSiteMapProvider.MV5 reference Asp.Net mvc4  ?

### ISSUE THREAD

**Issue by cdefg198** [maartenba/MvcSiteMapProvider#391]
Why MvcSiteMapProvider.MV5 reference Asp.Net mvc4  ?
My project is based Asp.Net mvc5,so Compile the project error。

**Comment by NightOwl888** [comment]
I am unable to reproduce your issue. [Here is a demo](https://github.com/NightOwl888/MvcSiteMapProvider_391) showing MvcSiteMapProvider working in an MVC5/VS2013 project.

Do note we do not yet have a package that works with MVC 6/ASP.NET 5. Could that be your issue?

**Comment by cdefg198** [comment]
Thanks @NightOwl888 ,I have to give up the use of the MvcSiteMapProvider,according to the MvcSiteMapProvider realize a little SiteMap.
Please forgive my poor English.
