### ISSUE TITLE
MVCSiteMapHtmlHelper.SiteMapPath's parameter startingNode

### ISSUE THREAD

**Issue by alonstar** [maartenba/MvcSiteMapProvider#400]
I tried to use @Html.MvcSiteMap().SiteMapPath() to build my website breadcrumb, and I wish it starts from the level 2 node, so I wrote

```
@Html.MvcSiteMap().SiteMapPath(MvcSiteMapProvider.SiteMaps.GetSiteMap().RootNode.ChildNodes[0])
```
But it doesn't start from the node, it end of the node. Is there anything wrong?

**Comment by NightOwl888** [comment]
For the SiteMapPath, the starting node is the last node. Normally, it is the current page and it shows all of the links from the current page to the top of the hierarchy (normally the home page). The order is reversed for display purposes, that is, it shows the home page as the first node and draws them to the current node.

So your example will always point to the first child of the root node regardless of what page you navigate to.

```
Home > 1st Child
```

If you want to hide the home page from the SiteMapPath, you should edit the `~/Views/Shared/DisplayTemplates/SiteMapPathHelperModel.cshtml` file. To get the result you want, you could do something like:

### Original

```cs
@model MvcSiteMapProvider.Web.Html.Models.SiteMapPathHelperModel
@using System.Web.Mvc.Html
@using System.Linq
@using MvcSiteMapProvider.Web.Html.Models

@foreach (var node in Model) { 
    @Html.DisplayFor(m => node);
    
    if (node != Model.Last()) {
        <text> &gt; </text>
    }
}
```

### Edit

```cs
@model MvcSiteMapProvider.Web.Html.Models.SiteMapPathHelperModel
@using System.Web.Mvc.Html
@using System.Linq
@using MvcSiteMapProvider.Web.Html.Models

@foreach (var node in Model) { 
    if (!node.IsRootNode) {
        @Html.DisplayFor(m => node);
    
        if (node != Model.Last()) {
            <text> &gt; </text>
        }
    }
}
```

Alternatively, you could use the [FilteredSiteMapNodeVisibilityProvider](https://github.com/maartenba/MvcSiteMapProvider/wiki/Advanced-Node-Visibility-with-ISiteMapNodeVisibilityProvider#using-filteredsitemapnodevisibilityprovider) to hide the visibility of the home page on the SiteMapPath.

```xml
<mvcSiteMapNode title="Home" controller="Home" action="Index" visibility="!SiteMapPathHelper" />
```
