### ISSUE TITLE
Sitemap without HttpContext

### ISSUE THREAD

**Issue by gaspardle** [maartenba/MvcSiteMapProvider#408]
Hi, 

Is it possible to retrieve the sitemap without having an HttpContext?

**Comment by NightOwl888** [comment]
No.

But you can fake it by creating your own instance of HttpContext as shown [here](https://github.com/maartenba/MvcSiteMapProvider/issues/278#issuecomment-34905271). We use that technique for both the `AuthorizeAttributeAclModule

**Comment by NightOwl888** [comment]
Closing as it appears this issue is resolved. Feel free to reopen if that is not the case.
