### ISSUE TITLE
SiteMaps.Current.FindSiteMapNodeFromCurrentContext() returns null 

### ISSUE THREAD

**Issue by AGuyCalledGerald** [maartenba/MvcSiteMapProvider#410]
I use the method SiteMaps.Current.FindSiteMapNodeFromCurrentContext() to return the current node. This does not work if the node has a custom attribute. If the custom attribute is empty or removed altogether, everything works fine. 
I use .Net MVC 5 and SitemapProvider v 4.6.18

**Comment by NightOwl888** [comment]
When using custom attributes, you must add them to the [AttributesToIgnore](https://github.com/maartenba/MvcSiteMapProvider/wiki/Using-Custom-Attributes-on-a-Node#ignoring-routevalues) configuration setting or they will automatically be taken into account when matching the node and when resolving the URL.

**Comment by AGuyCalledGerald** [comment]
Thank you, it works now.

**Comment by NightOwl888** [comment]
You're welcome.
