### ISSUE TITLE
Multiple sitemap files

### ISSUE THREAD

**Issue by arthurdpg** [maartenba/MvcSiteMapProvider#423]
Hi guys!

In my application I have two files .sitemap(Mvc.sitemap and MvcCustom.sitemap)
I need to use the MvcCustom.sitemap file in my view, but it keeps trying to render the Mvc.sitemap:

` <siteMap>
      <providers>
        <add name="MenuPrincipalMap" type="System.Web.XmlSiteMapProvider" siteMapFile="Mvc.sitemap"/>
        <add name="MenuSecundarioMap" type="System.Web.XmlSiteMapProvider" siteMapFile="MvcCustom.sitemap"/>
      </providers>
    </siteMap>`

` <div class="navbar-wrapper">
                <div class="navbar navbar-inverse" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("SYSTEM", "Index", "Home", null, new { @class = "navbar-brand" })
                    </div>
                    <div class="collapse navbar-collapse">
                        @Html.MvcSiteMap("MenuSecundarioiteMap").Menu("info", false, true, false)
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="shadow">
                        <ol class="breadcrumb">
                            @Html.MvcSiteMap("MenuSecundarioiteMap").SiteMapPath("info")
                        </ol>
                    </div>
                </div>
            </div>`

What's wrong?

**Comment by NightOwl888** [comment]
The `<sitemap>` section is not supported by `MvcSiteMapProvider` version 4. See [Upgrading from v3 to v4](https://github.com/maartenba/MvcSiteMapProvider/wiki/Upgrading-from-v3-to-v4).

There is a document covering this exact procedure called [Multiple SiteMaps in One Application](https://github.com/maartenba/MvcSiteMapProvider/wiki/Multiple-Sitemaps-in-One-Application). However, do note that there are better options for organizing nodes than to break them into different physical files, such as using [visibility providers](https://github.com/maartenba/MvcSiteMapProvider/wiki/Advanced-Node-Visibility-with-ISiteMapNodeVisibilityProvider).

Related:

- http://stackoverflow.com/questions/29751962/visibility-of-individual-items-in-mvcsitemapprovider
- http://stackoverflow.com/questions/23613197/how-to-add-multiple-sitemap-files-to-mvcsitemapprovider-during-session-start
- http://stackoverflow.com/questions/9436454/using-multiple-mvcsitemaps
- http://stackoverflow.com/questions/26541338/load-an-xml-sitemap-into-mvcsitemapprovider-based-on-user-role
- http://stackoverflow.com/questions/19387615/how-to-configure-multiple-sitemaps-using-using-mvcsitemapprovider-v4-with-unity
- http://stackoverflow.com/questions/19042744/using-asp-net-mvcsitemapprovider-v4-with-2-sitemap
- https://github.com/maartenba/MvcSiteMapProvider/issues/237
- https://github.com/maartenba/MvcSiteMapProvider/issues/215
