### ISSUE TITLE
Changes from "default" Autofac module

### ISSUE THREAD

**Issue by mwpowellhtx** [maartenba/MvcSiteMapProvider#428]
Hello,

When I installed for Autofac, code was dropped into my project in the path ``$(ProjectDir)DI/Autofac/Modules``. In and of itself, fair enough. However, I place these in an ``$(ProjectDir)Integration`` folder.

So, the question is, there wouldn't be a problem with me moving this code into my Integration folder?

Thank you...

**Comment by NightOwl888** [comment]
There is no problem at all with changing the configuration however it suits you. However, I would recommend not keeping the NuGet package in your project if you do this. See [these instructions](https://github.com/maartenba/MvcSiteMapProvider/issues/415#issuecomment-147108755) for getting the files into your project without the dependency on the NuGet package.

**Comment by mwpowellhtx** [comment]
Thanks for the suggestion to create a sync project. That'll help identity what's what.

**Comment by mwpowellhtx** [comment]
Another obvious question. ``Mvc.sitemap`` or ``Web.sitemap`` (i.e. if I had added one anticipating needing/wanting one, then found ``MvcSiteMapProvider``)?

Thank you...

**Comment by NightOwl888** [comment]
The default file name is `Mvc.sitemap`, but you can change its name and/or path by [editing the Autofac DI module directly](https://github.com/maartenba/MvcSiteMapProvider/blob/master/src/MvcSiteMapProvider/CodeAsConfiguration/Autofac/DI/Autofac/Modules/MvcSiteMapProviderModule.cs#L24).

**Comment by mwpowellhtx** [comment]
Yes, thank you. :+1:
