### ISSUE TITLE
Hirearchical menu seems to have lost its dropdowniness

### ISSUE THREAD

**Issue by mwpowellhtx** [maartenba/MvcSiteMapProvider#468]
Hello,

I'm probably missing something, but the menu rendering seems to have lost its "dropdowniness", so to speak.

That is, I see menus rendered as listed items but which are not collapsing. Perhaps there is a bootstrap style missing or that I need to further specify?

Thank you!

**Comment by maartenba** [comment]
The styling is *entirely*  up to you actually :-) We just render a simple list...

**Comment by mwpowellhtx** [comment]
I see what happened. I pulled the Core package in instead of the top level MVC5. It's been a little while working with this, like I said; getting my radar attenuated. :+1:
