### ISSUE TITLE
Interactive Resource Editing with 3rd Party Controls

### ISSUE THREAD

**Issue by NACIntlDev** [maartenba/MvcSiteMapProvider#486]
I am attempting to implement your Interactive Resource Editing strategy into an ASP.NET WebForms application that makes heavy use of 3rd party controls, DevExpress. The software is fully localized using Westwind, however, most of their  controls do not support the attributes 'data-resource-set' and 'data-resource-id', is there another way to markup the controls so that I can use your solution and/or LocalizationAdmin form to allow the user to edit resources.

Tks,
Alfonso

**Comment by NightOwl888** [comment]
Yes, there is another option - to implement [IStringLocalizer](https://stackoverflow.com/questions/25126620/globalization-in-mvcsitemapprovider/25139596#25139596) so you can provide your own resources to MvcSiteMapProvider.

**Comment by NACIntlDev** [comment]
Posted in the wrong area, this was meant as a question to WestWind.Globalization
