### ISSUE TITLE
Could not find file mvc.sitemap 

### ISSUE THREAD

**Issue by dailyUnknown** [maartenba/MvcSiteMapProvider#490]
Hello,

After installing MvcSiteMapProvider.mvc5 via nuget, I get an exception when running my mvc site via localhost and the error stating that "Could not find file 'C:\Users\...\Documents\Visual Studio 2017\Projects\....\Mvc.sitemap'."

I followed the intructions here: https://web.archive.org/web/20160424031041/http://www.shiningtreasures.com:80/post/2013/08/07/MvcSiteMapProvider-40-a-test-drive

I also add this @Html.MvcSiteMap().SiteMapPath() to the layout file but no breadcrumb displayed.

Anybody know why?

Note: The installation went fine and I can see the MvcSiteMapProvider.dll file in the bin folder.

Help please. Thank you.

**Comment by metalrose24** [comment]
You'll need to add the file to your project manually. The install via Nuget appears to be broken. You can take a sample of a site map file from the repo and go from there

**Comment by dailyUnknown** [comment]
Thank you metalrose24.
