### ISSUE TITLE
Breadcrumbs are not displayed correctly after publishing on PRD

### ISSUE THREAD

**Issue by joocker** [maartenba/MvcSiteMapProvider#493]
Hi,
I am using MvcSiteMapProvider in my MVC5 project. Everything works fine on localhost and on testing AP server, but after publishing onto production AP server, there is an issue how the breadcrumbs are displayed:

Localhost and testing environment look like;
![image](https://user-images.githubusercontent.com/59727627/72142081-3f654800-3394-11ea-8d1b-a4ca6e56076c.png)

Production looks like:
![image](https://user-images.githubusercontent.com/59727627/72142012-1ba20200-3394-11ea-9b47-13b11c6b62bb.png)

Have you seen this issue? Any advice is very appreciated. It is hard to debug this problem when on localhost everything is working just fine.

Thank you very much.

**Comment by metalrose24** [comment]
I had this same issue. It looks like something to do with the build via nuget is broken and it isn't inserting the views for the HTML helpers into your project as it should. 

I had to add the "DisplayTemplates" folder into Views/Shared myself. 

You can get the contents of the folder out the repository (one of the sample apps). 

After that it should work when deployed as well as locally.

**Comment by joocker** [comment]
> I had this same issue. It looks like something to do with the build via nuget is broken and it isn't inserting the views for the HTML helpers into your project as it should.
> 
> I had to add the "DisplayTemplates" folder into Views/Shared myself.
> 
> You can get the contents of the folder out the repository (one of the sample apps).
> 
> After that it should work when deployed as well as locally.

Thanks a lot. You were right. The views were not published in the DisplayTemplates folder.
